If (EDLISTBOXROW_L>0)
	EDLISTFORMEVENT_TXT:=fGetFormEvent
	C_TEXT:C284(EDLISTBOXFocusObject_txt)
	C_LONGINT:C283($Col)
	//RESOLVE POINTER(Focus object;EDLISTBOXFocusObject_txt)
	LISTBOX GET CELL POSITION:C971(EDITLISTBOX; $Col; EDLISTBOXROW_L)
	
	EDIT ITEM:C870(PvarInputs_atxt; EDLISTBOXROW_L)
End if 
