SCPOA_PrintSumm_L:=SCPOA_PrintSummbtn_L
SCPOA_PrintPOA_L:=SCPOA_PrintPOAbtn_L
SCPOA_PrintLocus_L:=SCPOA_PrintLocusbtn_L
SCPOA_PrintDetour_L:=SCPOA_PrintDetourbtn_L
SCPOA_PrintFLDNotes_L:=SCPOA_PrintFLDNotesbtn_L
SCPOA_PrintFVC_L:=SCPOA_PrintFVCBtn_L