//%attributes = {"invisible":true}
If (False:C215)
	// ----------------------------------------------------
	// User name (OS): costasmanousakis
	// User name (4D): Designer
	// Date and time: 07/01/11, 13:42:50
	// ----------------------------------------------------
	// Method: ARCHIVE_CondRptCtrl
	// Description
	//  ` Control the creation of a condition report based on the [BridgeMHDNBISArchive] table
	// 
	// Parameters
	// ----------------------------------------------------
	
	Mods_2011_06
End if 
//Get selection of records from the archive
QUERY:C277([BridgeMHDNBISArchive:139])
If ((OK=1) & (Records in selection:C76([BridgeMHDNBISArchive:139])>0))
	//Determine report to be run
	CONFIRM:C162("Run report for "+String:C10(Records in selection:C76([BridgeMHDNBISArchive:139]))+" records in the archive table?")
	If (OK=1)
		Startup_PL
		InitPrefs
		
		ut_RetrieveTOWNDATADoc
		
		G_InitCondRepVars
		CONFIRM:C162("Use the Legacy Owner for the Report?")
		STATREP_UseLegacyOwn_b:=(OK=1)
		C_TEXT:C284($DistrMethod_txt; $ReportCmt_txt)
		$DistrMethod_txt:=Request:C163("Choose Method for District calculations :"; "2")
		If ((OK=1) & (Num:C11($DistrMethod_txt)>0))
			STATREP_DistrictMethod_L:=Num:C11($DistrMethod_txt)  //use the OldDistrictNo3 info - 5 Districts
			C_TIME:C306($vTMStartTime; $vTMEndTime)
			$vTMStartTime:=Current time:C178(*)
			ARCHIVE_GenCondReport(True:C214)  //Do all NBI recs - live massages
			$vTMEndTime:=Current time:C178(*)
			$ReportCmt_txt:=Request:C163("Select report Comment :"; "Report From Archives Generated By "+Current user:C182+" .")
			[Status Report:69]Comments:135:=$ReportCmt_txt
			[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Started at "+String:C10($vTMStartTime)+"."
			[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Ended at "+String:C10($vTMEndTime)+"."
			
			SAVE RECORD:C53([Status Report:69])
			UNLOAD RECORD:C212([Status Report:69])
		End if 
	End if 
	
End if 