//%attributes = {"invisible":true}
//**********`Modified by: Costas Manousakis-(Designer)-(2023-06-07)
// CSLTINSP_ProceedWithLetter - copied from V18bug 2023-09-19
//  `when there are both NBI and Non-NBI bridges on list , ask for confirmation!
// ut_FixBINSequence - copied from V18bug 2023-09-19
//  `removed spurious call to ut_FixSequence

//Method: BrgRank_ImportRankCalc - copied from V18bug 2023-09-19
//Description
// Import Bridge rank calculation results from a text results file generated by`
// method BrgRank_DoRankCalc 

// [Personnel];"Inspectors In" - copied from V18bug 2023-09-19
//  fixed using the wrong name for PWUserHList object

// [Personnel];"Inspectors In".ToolsButton - copied from V18bug 2023-09-19
//  `allow access to changing password, groups and deactivating user only to design access group

//**********`Modified by: Costas Manousakis-(Designer)-(2023-06-15)
// LSS_ErrorMethod - copied from V18bug 2023-09-19
//  `Added Error method, line number and Error formula to the message

// SIA_FindMissingBDEPTs - copied from V18bug 2023-09-19
//  `To fix bug when searching in the current list of bridges, a new methodology was created.
//  ` implement some ORDA tools.
//  `when searching from a selection, it will find all towns in the selection and search in each 
//  `regardless whether all bridges for the towns are on the list.
//  `when asked to search for a specific town, show a list of towns to select from.

//**********`Modified by: Costas Manousakis-(Designer)-(2023-06-16)
// LB_ListContracts - copied from V18bug 2023-09-19
//  `when sorting by contract no , sort by formula Num(contract no)
//  `when a record has been deleted, clear the selection and try to keep the place in the listbox
//  `when closing a detail, release all other tables
// [Contracts];"Contracts_LB".Variable1 - copied from V18bug 2023-09-19
//  `Sort by number of contract no.
// [Contracts];"Contracts In" - copied from V18bug 2023-09-19
//  `changed _o_object set color with Object set rgb colors
//  `execute G_CalculateTLFandDE and G_ContractsCheckNegative only when record is not new when on Load event

//**********`Modified by: Costas Manousakis-(Designer)-(2023-06-20)
// [Parameters];"Input".EditJson - copied from V18bug 2023-09-19
//  `fix case where data returned from JSON editor is a collection - data was not saved

//**********`Modified by: Costas Manousakis-(Designer)-(2023-06-21)
// ut_OpenProjInfo_OM - copied from V18bug 2023-09-19
//  `adjusted logic to account for mac and use Storage so we don't have to check every time.


//```
//```    **** End of Release 8.0.2 2023-06-29
//```

//**********`Modified by: Costas Manousakis-(Designer)-(2023-06-30)
// INSP_ReviewAction - copied from V18bug 2023-09-19
//  `fixed error when area engineer is given choise to do a DBIE or an Area review. The action was the opposite of the user choice

