//%attributes = {"invisible":true}
If (False:C215)
	//Server_GenCondRep 
	//Method to be run as a Server Stored Provedure
	Mods_2005_CM07
	// Modified by: costasmanousakis-(Designer)-(5/10/2005 08:36:07)
	Mods_2005_CM12
	// Modified by: costasmanousakis-(Designer)-(6/2/2005 15:04:30)
	Mods_2005_CM13
	// Modified by: costasmanousakis-(Designer)-(10/17/2005 13:52:37)
	Mods_2005_CM17
	// Modified by: costasmanousakis-(Designer)-(11/23/2005 16:49:14)
	Mods_2005_CM19
	// Modified by: costasmanousakis-(Designer)-(11/2/09 12:25:45)
	Mods_2009_10("MASSDOT")
	//modified to generate two status reports , one with DOT ,one as using legacy owner
	// Modified by: costasmanousakis-(Designer)-(12/29/09 09:07:23)
	Mods_2009_12
	//Added code to initialize ptr_Changes and InitPrefs
	// Modified by: costasmanousakis-(Designer)-(6/16/10 11:21:12)
	Mods_2010_06
	//  `Added generation of a report using the new district distribution STATREP_DistrictMethod_b:=true
	// Modified by: costasmanousakis-(Designer)-(8/2/10 12:32:08)
	Mods_2010_08
	//  `Added the automatic emailing of the printed Bridge status reports and storing the data in archive tables
	//  `First test mail for the first few days.
	// Modified by: costasmanousakis-(Designer)-(8/4/10 16:53:10)
	Mods_2010_08
	//  `changed STATREP_DistrictMethod_b to STATREP_DistrictMethod_L
	//  `0 : false - previous default - uses 1st param Item2
	//  `1 : true - previous uses BDEPT and D6Towns array
	//  `2 : use BDEPT and get info from the [Town Data]District field
	//  `3 : use BDEPT and get info from the [Town Data]OldDistrictNo3 field. If it is blank use [Town Data]District
	
	// Modified by: costasmanousakis-(Designer)-(8/11/10 12:24:20)
	Mods_2010_08
	//  `Made code changes to use the new options 2,3 in STATREP_DistrNo
	//  `The data in [Town Data] was changed to the new D6 arrangement
	// Modified by: costasmanousakis-(Designer)-(3/1/11 16:40:41)
	Mods_2011_03
	//  `Added temporarily at the end call to ut_SRVMonthlyReports ("TEST") for execute on server
	// Modified by: costasmanousakis-(Designer)-(7/1/11 14:52:06)
	Mods_2011_06
	//  `Added creating a report with Somerville back to District 6 for comparison purposes after Jul-1-11
	// Modified by: Costas Manousakis-(Designer)-(5/16/13 08:43:20)
	Mods_2013_05
	//  `Added call to Server_SetItem75 to update item 75 before AASHTO is calculated (it affects item 67 whether it becomes a 3 or 2)
End if 
//TRACE
Startup_PL
//Array for changes
ARRAY POINTER:C280(ptr_Changes; 0; 0)
InitPrefs

INIT_UI_GV

ut_RetrieveTOWNDATADoc

C_TIME:C306($vTMStartTime; $vTMEndTime)
$vTMStartTime:=Current time:C178(*)

Server_SetItem75

ALL RECORDS:C47([Bridge MHD NBIS:1])
RecalcAASHTO(False:C215)
HI_CalcBridgeHIFields(False:C215)
REDUCE SELECTION:C351([Bridge MHD NBIS:1]; 0)
InitFOSDFields(False:C215)
G_InitCondRepVars

//AADDINGTESTFORBRI:=True
//set bridge table to RO
READ ONLY:C145([Bridge MHD NBIS:1])

STATREP_UseLegacyOwn_b:=False:C215
STATREP_DistrictMethod_L:=3  //use the OldDistrictNo3 info - 5 Districts
GenerateCondRep(False:C215; 2)  //Do all NBI recs ; Messages to file ??
$vTMEndTime:=Current time:C178(*)
[Status Report:69]Comments:135:="Report Generated By Server method."
[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Started at "+String:C10($vTMStartTime)+"."
[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Ended at "+String:C10($vTMEndTime)+"."

SAVE RECORD:C53([Status Report:69])
UNLOAD RECORD:C212([Status Report:69])

STATREP_UseLegacyOwn_b:=True:C214
STATREP_DistrictMethod_L:=3  //use the OldDistrictNo3 info - 5 Districts
$vTMStartTime:=Current time:C178(*)
GenerateCondRep(False:C215; 2)  //Do all NBI recs ; Messages to file ??
$vTMEndTime:=Current time:C178(*)
[Status Report:69]Comments:135:="Legacy Owner Report Generated By Server method."
[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Started at "+String:C10($vTMStartTime)+"."
[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Ended at "+String:C10($vTMEndTime)+"."

SAVE RECORD:C53([Status Report:69])
UNLOAD RECORD:C212([Status Report:69])

STATREP_UseLegacyOwn_b:=False:C215
STATREP_DistrictMethod_L:=2  //use the TownData District info - 6 Districts
$vTMStartTime:=Current time:C178(*)
GenerateCondRep(False:C215; 2)  //Do all NBI recs ; Messages to file ??
$vTMEndTime:=Current time:C178(*)
[Status Report:69]Comments:135:="Transition to 6 District Report Generated By Server method."
[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Started at "+String:C10($vTMStartTime)+"."
[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Ended at "+String:C10($vTMEndTime)+"."

SAVE RECORD:C53([Status Report:69])
UNLOAD RECORD:C212([Status Report:69])

STATREP_UseLegacyOwn_b:=False:C215
STATREP_DistrictMethod_L:=4  //use the TownData District info - 6 Districts except Move Somerville back to D6
$vTMStartTime:=Current time:C178(*)
GenerateCondRep(False:C215; 2)  //Do all NBI recs ; Messages to file ??
$vTMEndTime:=Current time:C178(*)
[Status Report:69]Comments:135:="6 District Report with Somerville back to D6 - Generated By Server method."
[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Started at "+String:C10($vTMStartTime)+"."
[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Ended at "+String:C10($vTMEndTime)+"."

SAVE RECORD:C53([Status Report:69])
UNLOAD RECORD:C212([Status Report:69])

//AADDINGTESTFORBRI:=True
STATREP_UseLegacyOwn_b:=False:C215
STATREP_DistrictMethod_L:=2  //use the TownData District info - 6 Districts
QUERY:C277([Bridge MHD NBIS:1]; [Bridge MHD NBIS:1]Item8 BridgeCat:207="BRI")
$vTMStartTime:=Current time:C178(*)
GenerateCondRep(True:C214; 2)  //use custom selection ; Messages to file 
$vTMEndTime:=Current time:C178(*)
[Status Report:69]Comments:135:="MADOT BRI Report Generated By Server method."
[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Started at "+String:C10($vTMStartTime)+"."
[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Ended at "+String:C10($vTMEndTime)+"."
SAVE RECORD:C53([Status Report:69])
UNLOAD RECORD:C212([Status Report:69])


C_TEXT:C284($vSCurrMo; $vsCurrYr)  // Command Replaced was o_C_STRING length was 8
$vsCurrYr:=String:C10(Year of:C25(Current date:C33(*)); "0000")
$vsCurrMo:=String:C10(Month of:C24(Current date:C33(*)); "00")
C_LONGINT:C283($vlSDHistRecs)
SET QUERY DESTINATION:C396(Into variable:K19:4; $vlSDHistRecs)
QUERY:C277([SD_History:89]; [SD_History:89]SD_Month:3=$vsCurrMo; *)
QUERY:C277([SD_History:89];  & ; [SD_History:89]SD_Year:2=$vsCurrYr)
SET QUERY DESTINATION:C396(Into current selection:K19:1)
If (($vlSDHistRecs=0) & ((Day number:C114(Current date:C33(*))>1) & (Day number:C114(Current date:C33(*))<7)))
	SD_CreateMonthlyData
End if 
If (Application type:C494=4D Server:K5:6)
	C_TEXT:C284($path; $YYYY_MM_DD)
	C_BLOB:C604($blobdoc)
	C_LONGINT:C283($err)
	$path:=ut_ReturnUserDocFolder("Exports")
	
	$YYYY_MM_DD:=String:C10(Year of:C25(Current date:C33(*)))+"_"+String:C10(Month of:C24(Current date:C33(*)))+"_"+String:C10(Day of:C23(Current date:C33(*)))
	
	If (Test path name:C476($path+"exprt sdfo.4si")=Is a document:K24:1)
		ALL RECORDS:C47([Bridge MHD NBIS:1])
		DOCUMENT TO BLOB:C525($path+"exprt sdfo.4si"; $blobdoc)
		EXPORT DATA:C666(($path+$YYYY_MM_DD+".dbf"); $blobdoc)
		REDUCE SELECTION:C351([Bridge MHD NBIS:1]; 0)
	End if 
	
	If (Test path name:C476($path+"sdonly_export.4si")=Is a document:K24:1)
		QUERY:C277([Bridge MHD NBIS:1]; [Bridge MHD NBIS:1]StructDef:103=True:C214)
		ORDER BY:C49([Bridge MHD NBIS:1]; [Bridge MHD NBIS:1]BDEPT:1; >; [Bridge MHD NBIS:1]BIN:3; >)
		DOCUMENT TO BLOB:C525($path+"sdonly_export.4si"; $blobdoc)
		EXPORT DATA:C666(($path+"SD_ONLY_"+$YYYY_MM_DD+".dbf"); $blobdoc)
		REDUCE SELECTION:C351([Bridge MHD NBIS:1]; 0)
	End if 
	SET BLOB SIZE:C606($blobdoc; 0)
	If (Day of:C23(Current date:C33(*))=1)
		ARCHIVE_Store("MONTHLYARCHIVE")
		ut_SRVMonthlyReports
	Else 
		ut_SRVMonthlyReports("TEST")
	End if 
	
End if 
ut_SetNextRunTimeStamp(Current method name:C684)