//%attributes = {"invisible":true}
// ----------------------------------------------------
// SRQ_SetUpPrint
// User name (OS): charlesmiller
// Date and time: 12/03/09, 10:58:37
// ----------------------------------------------------
// Description
// 
//
// Parameters
//$1 select Legacy or or not. If no param passed in assumption is that it is "Report Generated By Server method" 
// ----------------------------------------------------
If (False:C215)
	Mods_2009_12  // r001 CJ Miller`12/03/09, 11:49:44     `Costing changes re standards
	Mods_2009_12  // r001 CJ Miller`12/10/09, 17:07:20     `Integrate new status report
	Mods_2009_12  // r001 CJ Miller`12/17/09, 11:00:30        `Make changes to new status report
	//Make sure correct records are selected
	Mods_2009_12  // r001 CJ Miller`12/17/09, 14:31:21        `Make changes to new status report
	//Add Legacy status report
	Mods_2011_06  // CJ Miller`06/14/11, 13:25:05      ` Type all local variables for v11
End if 
//$LegacyFormName_txt:="LegacyStatusReport"
//$DOTFormName_txt:="QuarterlyStatusReport"
C_LONGINT:C283($Loop_l)
C_TEXT:C284($Selection_txt)
$Selection_txt:="Report Generated By Server method"
If (Count parameters:C259=1)
	C_TEXT:C284($1)
	If ($1="LegacyStatusReport")
		$Selection_txt:="Legacy Owner Report Generated By Server method"
	Else 
		$Selection_txt:="Report Generated By Server method"
	End if 
End if 
ARRAY LONGINT:C221($RecordsToReport_al; 0)
ARRAY LONGINT:C221($RecordsToReport_al; 4)
$RecordsToReport_al{4}:=Record number:C243([Status Report:69])
$RecordsToReport_al{3}:=-999
$RecordsToReport_al{2}:=-999
$RecordsToReport_al{1}:=-999
//identify prev qtrss and years
C_LONGINT:C283($CurrentYear_l; $CurrentMonth_l; $QueryMonth_l; $QueryYear_l)
$CurrentYear_l:=Year of:C25([Status Report:69]Date_Created:1)
$CurrentMonth_l:=Month of:C24([Status Report:69]Date_Created:1)
ARRAY DATE:C224($query_ad; 0)
ARRAY DATE:C224($query_ad; 3)

Case of 
	: ($CurrentMonth_l>=10)
		If (Day of:C23([Status Report:69]Date_Created:1)=1) & ($CurrentMonth_l=10)
			$query_ad{1}:=Date:C102("1/01/"+String:C10($CurrentYear_l))
		Else 
			$query_ad{1}:=Date:C102("4/01/"+String:C10($CurrentYear_l))
		End if 
		
	: ($CurrentMonth_l>=7)
		If (Day of:C23([Status Report:69]Date_Created:1)=1) & ($CurrentMonth_l=7)
			$query_ad{1}:=Date:C102("12/01/"+String:C10($CurrentYear_l-1))
		Else 
			$query_ad{1}:=Date:C102("1/01/"+String:C10($CurrentYear_l))
		End if 
	: ($CurrentMonth_l>=4)
		If (Day of:C23([Status Report:69]Date_Created:1)=1) & ($CurrentMonth_l=4)
			$query_ad{1}:=Date:C102("7/01/"+String:C10($CurrentYear_l-1))
		Else 
			$query_ad{1}:=Date:C102("12/01/"+String:C10($CurrentYear_l-1))
		End if 
	Else 
		If (Day of:C23([Status Report:69]Date_Created:1)=1) & ($CurrentMonth_l=1)
			$query_ad{1}:=Date:C102("4/01/"+String:C10($CurrentYear_l-1))
		Else 
			$query_ad{1}:=Date:C102("7/01/"+String:C10($CurrentYear_l-1))
		End if 
		
End case 
$query_ad{2}:=Add to date:C393($query_ad{1}; 0; 3; 0)
$query_ad{3}:=Add to date:C393($query_ad{2}; 0; 3; 0)
C_DATE:C307($Query_d)
C_BOOLEAN:C305($DateChanged_b)
$DateChanged_b:=False:C215
For ($Loop_l; 3; 1; -1)
	$Query_d:=$query_ad{$Loop_l}
	If ($1="QuarterlyStatusReport")
		If ($Query_d<!2009-11-01!)
			$Query_d:=!2009-11-01!
			If (Not:C34($DateChanged_b))
				$query_ad{$Loop_l}:=$Query_d
				$DateChanged_b:=True:C214
			End if 
		End if 
		
	End if 
	QUERY:C277([Status Report:69]; [Status Report:69]Date_Created:1>=$Query_d)
	
	
	QUERY SELECTION:C341([Status Report:69]; [Status Report:69]Owner:2="Designer")
	
	If ($Query_d>=!2009-11-01!)
		QUERY SELECTION:C341([Status Report:69]; [Status Report:69]Comments:135=$Selection_txt+"@")
	End if 
	ORDER BY:C49([Status Report:69]; [Status Report:69]Date_Created:1; >)
	C_BOOLEAN:C305($CorrectRecordFound_b)
	$CorrectRecordFound_b:=False:C215
	FIRST RECORD:C50([Status Report:69])
	C_LONGINT:C283($Position_l; $RecordNumber_l; $Position1_l)
	C_BOOLEAN:C305($UseFind_b)
	
	Repeat 
		$UseFind_b:=True:C214
		If ($1="LegacyStatusReport")
			If ($Query_d<!2009-11-01!)
				$UseFind_b:=False:C215
			End if 
		End if 
		$Position1_l:=Position:C15($Selection_txt; [Status Report:69]Comments:135)
		If (($Position1_l>0) | Not:C34($UseFind_b))
			$RecordNumber_l:=Record number:C243([Status Report:69])
			$Position_l:=Find in array:C230($RecordsToReport_al; $RecordNumber_l)
			If ($Position_l>0)
				$CorrectRecordFound_b:=True:C214
			Else 
				$RecordsToReport_al{$Loop_l}:=$RecordNumber_l
				$CorrectRecordFound_b:=True:C214
			End if 
		End if 
		NEXT RECORD:C51([Status Report:69])
	Until ($CorrectRecordFound_b)
	
End for 

If (Find in array:C230($RecordsToReport_al; -999)>0)
	ARRAY LONGINT:C221($SelectionArray_al; 0)
	
	For ($Loop_l; Size of array:C274($RecordsToReport_al); 1; -1)
		If ($RecordsToReport_al{$Loop_l}#-999)
			APPEND TO ARRAY:C911($SelectionArray_al; $RecordsToReport_al{$Loop_l})
		End if 
	End for 
	CREATE SELECTION FROM ARRAY:C640([Status Report:69]; $SelectionArray_al)
Else 
	CREATE SELECTION FROM ARRAY:C640([Status Report:69]; $RecordsToReport_al)
End if 

C_LONGINT:C283($FieldLoc_l; $Loop)

ARRAY TEXT:C222($FieldNames_atxt; 0)
ARRAY TEXT:C222($FieldNames_atxt; Get last field number:C255(69))
For ($Loop; 1; Get last field number:C255(69))
	$FieldNames_atxt{$Loop}:=Field name:C257(69; $Loop)
End for 

C_LONGINT:C283($RecordLoop_l; $InnerLoop_l)
C_POINTER:C301($Total_ptr; $SD_ptr; $SDPct_ptr; $Posted_ptr; $Closed_ptr; $Hi_Ptr)
C_POINTER:C301($TLTotal_ptr; $TLSD_ptr; $TLSDPct_ptr; $TLPosted_ptr; $TLClosed_ptr; $TLHi_Ptr)

C_POINTER:C301($FLDSD_ptr; $FLDPosted_ptr; $FLDClosed_ptr; $FLDHi_Ptr; $FLDTotal_ptr)

C_POINTER:C301($STTotal_ptr; $STSD_ptr; $STSDPct_ptr; $STPosted_ptr; $STClosed_ptr; $STHi_Ptr)
C_POINTER:C301($STTLTotal_ptr; $STTLSD_ptr; $STTSDPct_ptr; $STTLPosted_ptr; $STTlClosed_ptr; $STTLHi_Ptr)

C_POINTER:C301($GTLTotal_ptr; $GTLSD_ptr; $GTLSDPct_ptr; $GTLPosted_ptr; $GTLClosed_ptr; $GTLHi_Ptr)

C_POINTER:C301($QtrDate_ptr)

For ($RecordLoop_l; 4; 1; -1)
	If ($RecordsToReport_al{$RecordLoop_l}#-999)
		GOTO RECORD:C242([Status Report:69]; $RecordsToReport_al{$RecordLoop_l})
		//set up grand total line pointers
		$QtrDate_ptr:=Get pointer:C304("Quarter-"+String:C10($RecordLoop_l-1)+"_txt")
		$QtrDate_ptr->:=String:C10([Status Report:69]Date_Created:1; 7)
		Case of 
			: (Month of:C24([Status Report:69]Date_Created:1)>9)
				$QtrDate_ptr->:=$QtrDate_ptr->+" Quarter 4 - "
			: (Month of:C24([Status Report:69]Date_Created:1)>6)
				$QtrDate_ptr->:=$QtrDate_ptr->+" Quarter 3 - "
			: (Month of:C24([Status Report:69]Date_Created:1)>3)
				$QtrDate_ptr->:=$QtrDate_ptr->+" Quarter 2 - "
			Else 
				$QtrDate_ptr->:=$QtrDate_ptr->+" Quarter 1 - "
				
		End case 
		$QtrDate_ptr->:=$QtrDate_ptr->+String:C10(Year of:C25([Status Report:69]Date_Created:1))
		//$QtrDate_ptr->:=[Status Report]Date_Created
		//set up grand total pointers
		$GTLTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_GTTotal_l")
		$GTLSD_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_GTsd_l")
		$GTLSDPct_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_GTpsd_l")
		$GTLPosted_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_GTp_l")
		$GTLClosed_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_GTk_l")
		$GTLHi_Ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_GTHI_r")
		
		//set up total line pointers for state
		$TLTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+"Total_l")
		$TLSD_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+"Tsd_l")
		$TLSDPct_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+"Tpsd_l")
		$TLPosted_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+"Tp_l")
		$TLClosed_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+"Tk_l")
		$TLHi_Ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+"THI_r")
		
		//set up total line pointers for state / town
		
		$STTLTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STDTotal_l")
		$STTLSD_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STDTsd_l")
		$STTSDPct_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STDTpsd_l")
		$STTLPosted_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STDTp_l")
		$STTlClosed_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STDTk_l")
		$STTLHi_Ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STDTHI_r")
		
		//OK lets do State
		For ($InnerLoop_l; 1; 5)  //process for state
			//set pointers for state area
			$Total_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+String:C10($InnerLoop_l)+"Total_l")
			$SD_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+String:C10($InnerLoop_l)+"sd_l")
			$SDPct_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+String:C10($InnerLoop_l)+"psd_l")
			$Posted_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+String:C10($InnerLoop_l)+"p_l")
			$Closed_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+String:C10($InnerLoop_l)+"k_l")
			$Hi_Ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_SD"+String:C10($InnerLoop_l)+"HI_r")
			
			
			//set pointers for state a/ town area
			$STTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"Total_l")
			$STSD_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"sd_l")
			$STSDPct_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"psd_l")
			$STPosted_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"p_l")
			$STClosed_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"k_l")
			$STHi_Ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"HI_r")
			
			//set field pointers
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "S_D"+String:C10($InnerLoop_l)+"sd")
			$FLDSD_ptr:=Field:C253(69; $FieldLoc_l)
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "S_D"+String:C10($InnerLoop_l)+"p")
			$FLDPosted_ptr:=Field:C253(69; $FieldLoc_l)
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "S_D"+String:C10($InnerLoop_l)+"k")
			$FLDClosed_ptr:=Field:C253(69; $FieldLoc_l)
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "S_D"+String:C10($InnerLoop_l)+"_HI")
			$FLDHi_Ptr:=Field:C253(69; $FieldLoc_l)
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "S_D"+String:C10($InnerLoop_l)+"Total")
			$FLDTotal_ptr:=Field:C253(69; $FieldLoc_l)
			
			$Total_ptr->:=$FLDTotal_ptr->
			$SD_ptr->:=$FLDSD_ptr->
			$SDPct_ptr->:=f_BrgStatus_PCT($SD_ptr->; $Total_ptr->)
			$Posted_ptr->:=$FLDPosted_ptr->
			$Closed_ptr->:=$FLDClosed_ptr->
			$Hi_Ptr->:=$FLDHi_Ptr->
			
			//total line
			$TLTotal_ptr->:=$TLTotal_ptr->+$Total_ptr->
			$TLSD_ptr->:=$TLSD_ptr->+$SD_ptr->
			$TLPosted_ptr->:=$TLPosted_ptr->+$Posted_ptr->
			$TLClosed_ptr->:=$TLClosed_ptr->+$Closed_ptr->
			
			//Fill grand totals
			$GTLTotal_ptr->:=$GTLTotal_ptr->+$Total_ptr->
			$GTLSD_ptr->:=$GTLSD_ptr->+$SD_ptr->
			$GTLPosted_ptr->:=$GTLPosted_ptr->+$Posted_ptr->
			$GTLClosed_ptr->:=$GTLClosed_ptr->+$Closed_ptr->
			$GTLHi_Ptr->:=[Status Report:69]ALLBR_HI:160
			
			//individual lines for state/ town
			$STTotal_ptr->:=$STTotal_ptr->+$Total_ptr->
			$STSD_ptr->:=$STSD_ptr->+$SD_ptr->
			
			$STPosted_ptr->:=$STPosted_ptr->+$Posted_ptr->
			$STClosed_ptr->:=$STClosed_ptr->+$Closed_ptr->
			
			//total line for state and town
			$STTLTotal_ptr->:=$STTLTotal_ptr->+$Total_ptr->
			$STTLSD_ptr->:=$STTLSD_ptr->+$SD_ptr->
			$STTLPosted_ptr->:=$STTLPosted_ptr->+$Posted_ptr->
			$STTlClosed_ptr->:=$STTlClosed_ptr->+$Closed_ptr->
			//$STTLHi_Pt->r:=$STTLHi_Ptr->+
			
		End for 
		$TLSDPct_ptr->:=f_BrgStatus_PCT($TLSD_ptr->; $TLTotal_ptr->)
		$TLHi_Ptr->:=[Status Report:69]S_Tot_HI:141
		
		//OK lets do town
		
		//set up total line pointers for town
		$TLTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+"Total_l")
		$TLSD_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+"Tsd_l")
		$TLSDPct_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+"Tpsd_l")
		$TLPosted_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+"Tp_l")
		$TLClosed_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+"Tk_l")
		$TLHi_Ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+"THI_r")
		
		For ($InnerLoop_l; 1; 5)  //process for town
			//set pointers for town area
			$Total_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+String:C10($InnerLoop_l)+"Total_l")
			$SD_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+String:C10($InnerLoop_l)+"sd_l")
			$SDPct_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+String:C10($InnerLoop_l)+"psd_l")
			$Posted_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+String:C10($InnerLoop_l)+"p_l")
			$Closed_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+String:C10($InnerLoop_l)+"k_l")
			$Hi_Ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_TD"+String:C10($InnerLoop_l)+"HI_r")
			
			//set pointers for state a/ town area
			$STTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"Total_l")
			$STSD_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"sd_l")
			$STSDPct_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"psd_l")
			$STPosted_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"p_l")
			$STClosed_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"k_l")
			$STHi_Ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"HI_r")
			
			//set field pointers
			
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "T_D"+String:C10($InnerLoop_l)+"sd")
			$FLDSD_ptr:=Field:C253(69; $FieldLoc_l)
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "T_D"+String:C10($InnerLoop_l)+"p")
			$FLDPosted_ptr:=Field:C253(69; $FieldLoc_l)
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "T_D"+String:C10($InnerLoop_l)+"k")
			$FLDClosed_ptr:=Field:C253(69; $FieldLoc_l)
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "T_D"+String:C10($InnerLoop_l)+"_HI")
			$FLDHi_Ptr:=Field:C253(69; $FieldLoc_l)
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "T_D"+String:C10($InnerLoop_l)+"Total")
			$FLDTotal_ptr:=Field:C253(69; $FieldLoc_l)
			
			$Total_ptr->:=$FLDTotal_ptr->
			$SD_ptr->:=$FLDSD_ptr->
			$SDPct_ptr->:=f_BrgStatus_PCT($SD_ptr->; $Total_ptr->)
			$Posted_ptr->:=$FLDPosted_ptr->
			$Closed_ptr->:=$FLDClosed_ptr->
			$Hi_Ptr->:=$FLDHi_Ptr->
			
			//total line
			$TLTotal_ptr->:=$TLTotal_ptr->+$Total_ptr->
			$TLSD_ptr->:=$TLSD_ptr->+$SD_ptr->
			$TLPosted_ptr->:=$TLPosted_ptr->+$Posted_ptr->
			$TLClosed_ptr->:=$TLClosed_ptr->+$Closed_ptr->
			$TLHi_Ptr->:=$TLHi_Ptr->+$Hi_Ptr->
			
			//individual lines for state/ town
			$STTotal_ptr->:=$STTotal_ptr->+$Total_ptr->
			$STSD_ptr->:=$STSD_ptr->+$SD_ptr->
			$STSDPct_ptr->:=f_BrgStatus_PCT($STSD_ptr->; $STTotal_ptr->)
			$STPosted_ptr->:=$STPosted_ptr->+$Posted_ptr->
			$STClosed_ptr->:=$STClosed_ptr->+$Closed_ptr->
			
			//Fill grand totals
			$GTLTotal_ptr->:=$GTLTotal_ptr->+$Total_ptr->
			$GTLSD_ptr->:=$GTLSD_ptr->+$SD_ptr->
			$GTLPosted_ptr->:=$GTLPosted_ptr->+$Posted_ptr->
			$GTLClosed_ptr->:=$GTLClosed_ptr->+$Closed_ptr->
			
			//total line for state and town
			$STTLTotal_ptr->:=$STTLTotal_ptr->+$Total_ptr->
			$STTLSD_ptr->:=$STTLSD_ptr->+$SD_ptr->
			$STTLPosted_ptr->:=$STTLPosted_ptr->+$Posted_ptr->
			$STTlClosed_ptr->:=$STTlClosed_ptr->+$Closed_ptr->
			$STTSDPct_ptr->:=f_BrgStatus_PCT($STTLSD_ptr->; $STTLTotal_ptr->)
			
		End for 
		$TLSDPct_ptr->:=f_BrgStatus_PCT($TLSD_ptr->; $TLTotal_ptr->)
		
		$TLHi_Ptr->:=[Status Report:69]T_Tot_HI:147
		
		$TLTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+"Total_l")
		$TLSD_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+"Tsd_l")
		$TLSDPct_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+"Tpsd_l")
		$TLPosted_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+"Tp_l")
		$TLClosed_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+"Tk_l")
		$TLHi_Ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+"THI_r")
		
		For ($InnerLoop_l; 1; 5)  //process for STATE AND TOWN HI TOTALS
			//set field pointers
			
			$FieldLoc_l:=Find in array:C230($FieldNames_atxt; "S_T_D"+String:C10($InnerLoop_l)+"_HI")
			$FLDHi_Ptr:=Field:C253(69; $FieldLoc_l)
			
			$STHi_Ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_STD"+String:C10($InnerLoop_l)+"HI_r")
			$STHi_Ptr->:=$FLDHi_Ptr->
			$Hi_Ptr->:=$STHi_Ptr->
			
			//total line
		End for 
		$TLHi_Ptr->:=[Status Report:69]S_T_Tot_HI:153
		//process misc lines
		C_POINTER:C301($MiscTotal_ptr; $Miscsd_ptr; $Miscpsd_ptr; $Miscp_ptr; $Misck_ptr; $MiscHI_ptr)
		If ($Selection_txt="Legacy Owner Report Generated By Server method")
			$MiscTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MTATotal_l")
			$Miscsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MTAsd_l")
			$Miscpsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MTApsd_l")
			$Miscp_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MTAp_l")
			$Misck_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MTAk_l")
			$MiscHI_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MTAHI_r")
			//This section only for legacy report which has one additional line on the form
			$MiscTotal_ptr->:=[Status Report:69]MTA_total:15
			$Miscsd_ptr->:=[Status Report:69]MTA_sd:32
			$Miscp_ptr->:=[Status Report:69]MTA_p:66
			$Miscpsd_ptr->:=f_BrgStatus_PCT($Miscsd_ptr->; $MiscTotal_ptr->)
			$Misck_ptr->:=[Status Report:69]MTA_k:83
			$MiscHI_ptr->:=[Status Report:69]MTA_HI:156
			$GTLTotal_ptr->:=$GTLTotal_ptr->+$MiscTotal_ptr->
			$GTLSD_ptr->:=$GTLSD_ptr->+$Miscsd_ptr->
			$GTLPosted_ptr->:=$GTLPosted_ptr->+$Miscp_ptr->
			$GTLClosed_ptr->:=$GTLClosed_ptr->+$Misck_ptr->
			
		End if 
		//get MBTA
		$MiscTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MBTATotal_l")
		$Miscsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MBTAsd_l")
		$Miscpsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MBTApsd_l")
		$Miscp_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MBTAp_l")
		$Misck_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MBTAk_l")
		$MiscHI_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MBTAHI_r")
		
		$MiscTotal_ptr->:=[Status Report:69]MBTA_total:13
		$Miscsd_ptr->:=[Status Report:69]MBTA_sd:30
		$Miscp_ptr->:=[Status Report:69]MBTA_p:64
		$Miscpsd_ptr->:=f_BrgStatus_PCT($Miscsd_ptr->; $MiscTotal_ptr->)
		$Misck_ptr->:=[Status Report:69]MBTA_k:81
		$MiscHI_ptr->:=[Status Report:69]MBTA_HI:154
		
		$GTLTotal_ptr->:=$GTLTotal_ptr->+$MiscTotal_ptr->
		$GTLSD_ptr->:=$GTLSD_ptr->+$Miscsd_ptr->
		$GTLPosted_ptr->:=$GTLPosted_ptr->+$Miscp_ptr->
		$GTLClosed_ptr->:=$GTLClosed_ptr->+$Misck_ptr->
		
		//get  DCR (MDC)
		
		$MiscTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DCRTotal_l")
		$Miscsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DCRsd_l")
		$Miscpsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DCRpsd_l")
		$Miscp_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DCRp_l")
		$Misck_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DCRk_l")
		$MiscHI_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DCRHI_r")
		
		$MiscTotal_ptr->:=[Status Report:69]MDC_total:14
		$Miscsd_ptr->:=[Status Report:69]MDC_sd:31
		$Miscp_ptr->:=[Status Report:69]MDC_p:65
		$Miscpsd_ptr->:=f_BrgStatus_PCT($Miscsd_ptr->; $MiscTotal_ptr->)
		$Misck_ptr->:=[Status Report:69]MDC_k:82
		$MiscHI_ptr->:=[Status Report:69]MDC_HI:155
		
		$GTLTotal_ptr->:=$GTLTotal_ptr->+$MiscTotal_ptr->
		$GTLSD_ptr->:=$GTLSD_ptr->+$Miscsd_ptr->
		$GTLPosted_ptr->:=$GTLPosted_ptr->+$Miscp_ptr->
		$GTLClosed_ptr->:=$GTLClosed_ptr->+$Misck_ptr->
		
		//get  MPA
		
		$MiscTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MPATotal_l")
		$Miscsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MPAsd_l")
		$Miscpsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MPApsd_l")
		$Miscp_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MPAp_l")
		$Misck_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MPAk_l")
		$MiscHI_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_MPAHI_r")
		
		$MiscTotal_ptr->:=[Status Report:69]MPA_total:16
		$Miscsd_ptr->:=[Status Report:69]MPA_sd:33
		$Miscp_ptr->:=[Status Report:69]MPA_p:67
		$Miscpsd_ptr->:=f_BrgStatus_PCT($Miscsd_ptr->; $MiscTotal_ptr->)
		$Misck_ptr->:=[Status Report:69]MPA_k:84
		$MiscHI_ptr->:=[Status Report:69]MPA_HI:157
		
		$GTLTotal_ptr->:=$GTLTotal_ptr->+$MiscTotal_ptr->
		$GTLSD_ptr->:=$GTLSD_ptr->+$Miscsd_ptr->
		$GTLPosted_ptr->:=$GTLPosted_ptr->+$Miscp_ptr->
		$GTLClosed_ptr->:=$GTLClosed_ptr->+$Misck_ptr->
		
		//get DEM
		
		$MiscTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DEMTotal_l")
		$Miscsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DEMsd_l")
		$Miscpsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DEMpsd_l")
		$Miscp_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DEMp_l")
		$Misck_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DEMk_l")
		$MiscHI_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_DEMHI_r")
		
		$MiscTotal_ptr->:=[Status Report:69]DEM_total:17
		$Miscsd_ptr->:=[Status Report:69]DEM_sd:34
		$Miscp_ptr->:=[Status Report:69]DEM_p:68
		$Miscpsd_ptr->:=f_BrgStatus_PCT($Miscsd_ptr->; $MiscTotal_ptr->)
		$Misck_ptr->:=[Status Report:69]DEM_k:85
		$MiscHI_ptr->:=[Status Report:69]DEM_HI:158
		
		$GTLTotal_ptr->:=$GTLTotal_ptr->+$MiscTotal_ptr->
		$GTLSD_ptr->:=$GTLSD_ptr->+$Miscsd_ptr->
		$GTLPosted_ptr->:=$GTLPosted_ptr->+$Miscp_ptr->
		$GTLClosed_ptr->:=$GTLClosed_ptr->+$Misck_ptr->
		
		//get Oth (DNR)
		
		$MiscTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_OTHTotal_l")
		$Miscsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_OTHsd_l")
		$Miscpsd_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_OTHpsd_l")
		$Miscp_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_OTHp_l")
		$Misck_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_OTHk_l")
		$MiscHI_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_OTHHI_r")
		
		$MiscTotal_ptr->:=[Status Report:69]DNR_total:18
		$Miscsd_ptr->:=[Status Report:69]DNR_t:103
		$Miscp_ptr->:=[Status Report:69]DNR_p:69
		$Miscpsd_ptr->:=f_BrgStatus_PCT($Miscsd_ptr->; $MiscTotal_ptr->)
		$Misck_ptr->:=[Status Report:69]DNR_k:86
		$MiscHI_ptr->:=[Status Report:69]OTHER_HI:159
		
		$GTLTotal_ptr->:=$GTLTotal_ptr->+$MiscTotal_ptr->
		$GTLSD_ptr->:=$GTLSD_ptr->+$Miscsd_ptr->
		$GTLPosted_ptr->:=$GTLPosted_ptr->+$Miscp_ptr->
		$GTLClosed_ptr->:=$GTLClosed_ptr->+$Misck_ptr->
	Else 
		
		
		
		
		$QtrDate_ptr:=Get pointer:C304("Quarter-"+String:C10($RecordLoop_l-1)+"_txt")
		$QtrDate_ptr->:=""
		Case of 
			: (Month of:C24($query_ad{$RecordLoop_l})>9)
				$QtrDate_ptr->:=$QtrDate_ptr->+" Quarter 4 - "
			: (Month of:C24($query_ad{$RecordLoop_l})>6)
				$QtrDate_ptr->:=$QtrDate_ptr->+" Quarter 3 - "
			: (Month of:C24($query_ad{$RecordLoop_l})>3)
				$QtrDate_ptr->:=$QtrDate_ptr->+" Quarter 2 - "
			Else 
				$QtrDate_ptr->:=$QtrDate_ptr->+" Quarter 1 - "
				
		End case 
		$QtrDate_ptr->:="No Records "+$QtrDate_ptr->+String:C10($query_ad{$RecordLoop_l})
		
		
	End if 
End for 
For ($RecordLoop_l; 4; 1; -1)  //lets set the Grand total %
	
	If ($RecordsToReport_al{$RecordLoop_l}#-999)
		$GTLSDPct_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_GTpsd_l")
		$GTLTotal_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_GTTotal_l")
		$GTLSD_ptr:=Get pointer:C304("Q"+String:C10($RecordLoop_l-1)+"_GTsd_l")
		
		$GTLSDPct_ptr->:=f_BrgStatus_PCT($GTLSD_ptr->; $GTLTotal_ptr->)
	Else 
		$GTLSDPct_ptr->:=0
	End if 
End for 

//End SRQ_SetUpPrint