//%attributes = {"invisible":true}
If (False:C215)
	// ----------------------------------------------------
	// User name (OS): costasmanousakis
	// User name (4D): Designer
	// Date and time: 06/28/11, 15:54:33
	// ----------------------------------------------------
	// Method: Temp_SomrvileToD4
	// Description
	//  ` Transfer Sommervi bridges to D4 Item 2 and Insp Resp -
	//  `Run once
	// 
	// Parameters
	// ----------------------------------------------------
	
	Mods_2011_06
End if 
If (User in group:C338(Current user:C182; "Design Access Group"))
	QUERY:C277([Bridge MHD NBIS:1]; [Bridge MHD NBIS:1]BDEPT:1="S17@")
	C_BOOLEAN:C305($GoToD4)
	CONFIRM:C162("Move "+String:C10(Records in selection:C76([Bridge MHD NBIS:1]))+"  to D4 or Back to D6?"; "D4"; "D6")
	$GoToD4:=(OK=1)
	If ($GoToD4)
		FIRST RECORD:C50([Bridge MHD NBIS:1])
		While (Not:C34(End selection:C36([Bridge MHD NBIS:1])))
			If ([Bridge MHD NBIS:1]Item2:60#"04")
				If (ut_LoadRecordInteractive(->[Bridge MHD NBIS:1]))
					InitChangeStack(1)
					[Bridge MHD NBIS:1]Item2:60:="04"
					PushChange(1; ->[Bridge MHD NBIS:1]Item2:60)
					If (([Bridge MHD NBIS:1]InspResp:173="DIST6") | ([Bridge MHD NBIS:1]InspResp:173="MTA"))
						[Bridge MHD NBIS:1]InspResp:173:="DIST4"
						PushChange(1; ->[Bridge MHD NBIS:1]InspResp:173)
					End if 
					
					FlushGrpChgs(1; ->[Bridge MHD NBIS:1]BIN:3; ->[Bridge MHD NBIS:1]BIN:3; ->[Bridge MHD NBIS:1]BIN:3; 0)
					SAVE RECORD:C53([Bridge MHD NBIS:1])
				End if 
				
			End if 
			
			NEXT RECORD:C51([Bridge MHD NBIS:1])
			
		End while 
		QUERY:C277([Town Data:2]; [Town Data:2]Town Name:1="Somerville")
		If (ut_LoadRecordInteractive(->[Town Data:2]))
			InitChangeStack(1)
			[Town Data:2]District:6:="04"
			PushChange(1; ->[Town Data:2]District:6)
			FlushGrpChgs(1; ->[Town Data:2]BDEPT Prefix:2; ->[Town Data:2]BDEPT Prefix:2; ->[Town Data:2]BDEPT Prefix:2; 0)
			SAVE RECORD:C53([Town Data:2])
		End if 
		CONFIRM:C162("Execute a New Report?"; "NEW"; "Cancel")
		If (OK=1)
			InitPrefs
			
			ut_RetrieveTOWNDATADoc
			G_InitCondRepVars
			STATREP_UseLegacyOwn_b:=False:C215
			STATREP_DistrictMethod_L:=2  //use the TownData District info - 6 Districts
			C_TIME:C306($vTMStartTime; $vTMEndTime)
			$vTMStartTime:=Current time:C178(*)
			GenerateCondRep(False:C215)  //Do all NBI recs ; Messages to file ??
			$vTMEndTime:=Current time:C178(*)
			[Status Report:69]Comments:135:="1st Day of Somerville in D4 Generated By Server method."
			[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Started at "+String:C10($vTMStartTime)+"."
			[Status Report:69]Comments:135:=[Status Report:69]Comments:135+" Ended at "+String:C10($vTMEndTime)+"."
			
			SAVE RECORD:C53([Status Report:69])
			UNLOAD RECORD:C212([Status Report:69])
		End if 
		
	Else 
		FIRST RECORD:C50([Bridge MHD NBIS:1])
		While (Not:C34(End selection:C36([Bridge MHD NBIS:1])))
			If ([Bridge MHD NBIS:1]Item2:60#"06")
				If (ut_LoadRecordInteractive(->[Bridge MHD NBIS:1]))
					InitChangeStack(1)
					[Bridge MHD NBIS:1]Item2:60:="06"
					PushChange(1; ->[Bridge MHD NBIS:1]Item2:60)
					
					FlushGrpChgs(1; ->[Bridge MHD NBIS:1]BIN:3; ->[Bridge MHD NBIS:1]BIN:3; ->[Bridge MHD NBIS:1]BIN:3; 0)
					SAVE RECORD:C53([Bridge MHD NBIS:1])
				End if 
				
			End if 
			
			NEXT RECORD:C51([Bridge MHD NBIS:1])
			
		End while 
		QUERY:C277([Town Data:2]; [Town Data:2]Town Name:1="Somerville")
		If (ut_LoadRecordInteractive(->[Town Data:2]))
			InitChangeStack(1)
			[Town Data:2]District:6:="06"
			PushChange(1; ->[Town Data:2]District:6)
			FlushGrpChgs(1; ->[Town Data:2]BDEPT Prefix:2; ->[Town Data:2]BDEPT Prefix:2; ->[Town Data:2]BDEPT Prefix:2; 0)
			SAVE RECORD:C53([Town Data:2])
		End if 
		
	End if 
	UNLOAD RECORD:C212([Bridge MHD NBIS:1])
	UNLOAD RECORD:C212([Town Data:2])
End if 
