//%attributes = {"invisible":true}
If (False:C215)
	// ----------------------------------------------------
	// User name (OS): costasmanousakis
	// User name (4D): Designer
	// Date and time: 08/22/07, 08:50:22
	// ----------------------------------------------------
	// Method: ut_SetMessageDir
	// Description
	// Define the full name of the directory where the files generated by the ut_StartMessage
	// method will be created.  If folder does not exist, it will be created.
	// 
	// Parameters
	// $1 : $FolderName_txt : name of the folder.
	//  `Passing zero length string, will clear the variable
	// ----------------------------------------------------
	
	Mods_2007_CM12_5301
	Mods_2011_05  //r002 CJ Miller`05/20/11, 12:08:33      `Change directory where exports are stored to the users documents folder
	// Modified by: Costas Manousakis-(Designer)-(11/19/19 12:29:40)
	Mods_2019_11
	//  `always create folders under the users documents folder - 
	//  `also no need to create any folders here because all are created in ut_ReturnUserDocFolder
End if 
C_TEXT:C284($1; $FolderName_txt)
$FolderName_txt:=$1
C_TEXT:C284(MessageDefDir_txt)

If ($FolderName_txt#"")
	If (False:C215)
		
		Case of 
			: (Application type:C494=4D Server:K5:6) | (<>MacPL_b)
				MessageDefDir_txt:=ut_ReturnUserDocFolder($FolderName_txt)
				
			: (Application type:C494=4D Local mode:K5:1)  //| (Application type=_o_4D Interpreted desktop))
				//next to structure file
				MessageDefDir_txt:=GetPath(Structure file:C489)
			: (Application type:C494=4D Volume desktop:K5:2)
				MessageDefDir_txt:=GetPath(Application file:C491)
			: (Application type:C494=4D Remote mode:K5:5)
				//next to application
				MessageDefDir_txt:=GetPath(Application file:C491)
		End case 
		
	End if 
	//always create folders under the users documents folder
	MessageDefDir_txt:=ut_ReturnUserDocFolder($FolderName_txt)
	
	If (False:C215)
		If ((Application type:C494=4D Server:K5:6) | (<>MacPL_b))
		Else 
			C_LONGINT:C283($k)
			C_TEXT:C284($SubPath_txt)
			Repeat 
				$k:=Position:C15(Folder separator:K24:12; $FolderName_txt)
				If ($k>0)
					$SubPath_txt:=Substring:C12($FolderName_txt; 1; ($k-1))
					$FolderName_txt:=Substring:C12($FolderName_txt; ($k+1))
				Else 
					$SubPath_txt:=$FolderName_txt
					$FolderName_txt:=""
				End if 
				MessageDefDir_txt:=MessageDefDir_txt+$SubPath_txt+Folder separator:K24:12
				If (Test path name:C476(MessageDefDir_txt)=Is a folder:K24:2)
				Else 
					CREATE FOLDER:C475(MessageDefDir_txt)
				End if 
				
			Until ($FolderName_txt="")
		End if 
		
	End if 
Else 
	MessageDefDir_txt:=""
End if 