C_LONGINT:C283(PON_PARENTENV_L; PON_PARENTSTRUNIT_L; PON_PARENTKEY_L; PON_GRANDPARENTKEY_L)
C_BOOLEAN:C305(PON_ADDPROTSYS_b)
PON_PARENTENV_L:=0
PON_PARENTSTRUNIT_L:=0
PON_PARENTKEY_L:=0
PON_GRANDPARENTKEY_L:=0
PON_ADDPROTSYS_b:=False:C215
//ALERT("Add New NBE ELEMENT!")
//need to have a BMS inspection record

ADD RECORD:C56([NTI_ELEM_BIN_INSP:183])
If (OK=1)
	NTI_ListElements
End if 

//set to no parent after adding
PON_PARENTKEY_L:=0
