POPUPMENUC(Self:C308; Self:C308; ->PURPOSE_TXT)
If (PURPOSE_TXT="NEWPURPOSE")
	PURPOSE_TXT:=""
	OBJECT SET ENTERABLE:C238(*; "PURPOSE_TXT"; True:C214)
	GOTO OBJECT:C206(*; "PURPOSE_TXT")
	ARRAY TEXT:C222(SUBCATEGLIST_ATXT; 0)
	ARRAY TEXT:C222(EXISTITEMSLIST_ATXT; 0)
	SUBCATEGORY_TXT:=""
Else 
	SUBCATEGORY_TXT:=""
	ARRAY TEXT:C222(SUBCATEGLIST_ATXT; 0)
	ARRAY TEXT:C222(EXISTITEMSLIST_ATXT; 0)
	QUERY:C277([zSpecialReports:106]; [zSpecialReports:106]Purpose:1=PURPOSE_TXT)
	DISTINCT VALUES:C339([zSpecialReports:106]SubCategory:5; SUBCATEGLIST_ATXT)
	QUERY:C277([zSpecialReports:106]; [zSpecialReports:106]Purpose:1=PURPOSE_TXT)
	QUERY SELECTION:C341([zSpecialReports:106]; [zSpecialReports:106]SubCategory:5="")
	SELECTION TO ARRAY:C260([zSpecialReports:106]ReportName:2; EXISTITEMSLIST_ATXT)
	SORT ARRAY:C229(EXISTITEMSLIST_ATXT)
	SORT ARRAY:C229(SUBCATEGLIST_ATXT)
	INSERT IN ARRAY:C227(SUBCATEGLIST_ATXT; 1; 1)
	SUBCATEGLIST_ATXT{1}:="NEWCATEGORY"
	INSERT IN ARRAY:C227(SUBCATEGLIST_ATXT; 1; 1)
	SUBCATEGLIST_ATXT{1}:="No Category"
	OBJECT SET ENABLED:C1123(*; "SUBCATEGLIST_ATXT@"; True:C214)  // Command Replaced was o_ENABLE BUTTON 
	OBJECT SET ENTERABLE:C238(*; "MENUNAME_TXT"; True:C214)
	OBJECT SET ENTERABLE:C238(*; "REPORTNAME_TXT"; True:C214)
	OBJECT SET ENTERABLE:C238(*; "LONGDESCR_TXT"; True:C214)
	OBJECT SET ENTERABLE:C238(*; "TEMPLDESCR_TXT"; True:C214)
	OBJECT SET ENABLED:C1123(*; "SOURCEFILEbtn@"; True:C214)  // Command Replaced was o_ENABLE BUTTON 
End if 
