Case of 
	: (Form event code:C388=On Load:K2:1)
		
	: (Form event code:C388=On Data Change:K2:15)
		//round total q to PON_RoundQ_L dec
		[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21:=Round:C94([NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundQ_L)
		// when changing total q-subtract from it quantities for st2-3-4  and put rest in st 1 or 2
		If ([NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21<=0)
			ALERT:C41("Cannot change to Zero Quantity!")
			[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21:=Old:C35([NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21)
		Else 
			//make sure state fields are enterable
			OBJECT SET ENTERABLE:C238(*; "DE ELEM_QTYSTATE@"; True:C214)
			OBJECT SET ENTERABLE:C238(*; "DE ELEM_PCTSTATE@"; True:C214)
			OBJECT SET RGB COLORS:C628(*; "DE ELEM_QTYSTATE@"; Col_paletteToRGB(Abs:C99(PON_Color_Editable_L)%256); Col_paletteToRGB(Abs:C99(PON_Color_Editable_L)\256))  // **Replaced o OBJECT SET COLOR(*; "DE ELEM_QTYSTATE@"; PON_Color_Editable_L)
			OBJECT SET RGB COLORS:C628(*; "DE ELEM_PCTSTATE@"; Col_paletteToRGB(Abs:C99(PON_Color_Editable_L)%256); Col_paletteToRGB(Abs:C99(PON_Color_Editable_L)\256))  // **Replaced o OBJECT SET COLOR(*; "DE ELEM_PCTSTATE@"; PON_Color_Editable_L)
			//also now enable quant and percent radio buttons
			//_ o _ENABLE BUTTON(*;"DE bQuantity")
			//_ o _ENABLE BUTTON(*;"DE bPercent")
			OBJECT SET ENABLED:C1123(*; "DE bQuantity"; True:C214)
			OBJECT SET ENABLED:C1123(*; "DE bPercent"; True:C214)
			
			If ([NTI_ELEM_BIN_INSP:183]ELEM_PARENT_KEY:7=0)
				//primary element - Q1 state is not enterable
				OBJECT SET ENTERABLE:C238(*; "DE ELEM_QTYSTATE1"; False:C215)
				OBJECT SET ENTERABLE:C238(*; "DE ELEM_PCTSTATE1"; False:C215)
				OBJECT SET RGB COLORS:C628(*; "DE ELEM_QTYSTATE1"; Col_paletteToRGB(Abs:C99(PON_Color_NOTEditable_L)%256); Col_paletteToRGB(Abs:C99(PON_Color_NOTEditable_L)\256))  // **Replaced o OBJECT SET COLOR(*; "DE ELEM_QTYSTATE1"; PON_Color_NOTEditable_L)
				OBJECT SET RGB COLORS:C628(*; "DE ELEM_PCTSTATE1"; Col_paletteToRGB(Abs:C99(PON_Color_NOTEditable_L)%256); Col_paletteToRGB(Abs:C99(PON_Color_NOTEditable_L)\256))  // **Replaced o OBJECT SET COLOR(*; "DE ELEM_PCTSTATE1"; PON_Color_NOTEditable_L)
				
				If ([NTI_ELEM_BIN_INSP:183]ELEM_QorP:16)
					
					[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE1:17:=[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20
					If ([NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE1:17<0)
						// Warn that there is an error!
						ALERT:C41("Quantities in States do not add up correctly with Total Quantity!!! Please Adjust!")
					End if 
					[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
					[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE3:14:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
					[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE4:15:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
					[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE1:12:=100-[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13-[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE3:14-[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE4:15
					
				Else 
					//if we are showing Percentages - recalc quantities based on percentages leave percentages as is
					[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19:=Round:C94((([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE3:14*[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21)/100); PON_RoundQ_L)
					[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20:=Round:C94((([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE4:15*[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21)/100); PON_RoundQ_L)
					[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18:=Round:C94((([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13*[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21)/100); PON_RoundQ_L)
					[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE1:17:=[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20
					If ([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE1:12=0)
						[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE1:12:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE1:17/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
					Else 
						ALERT:C41("Quantities in States 1,2,3,4 adjusted according to current Percentages!")
					End if 
					
				End if 
				
			Else 
				//defect
				If (PON_ElemNoQuantState1_b)
					//lock pct fields for state 2 ; and qty for st 1 qty is enabled
					OBJECT SET ENTERABLE:C238([NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE1:17; False:C215)
					OBJECT SET ENTERABLE:C238([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13; False:C215)
					OBJECT SET RGB COLORS:C628([NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE1:17; Col_paletteToRGB(Abs:C99(PON_Color_NotEditable_L)%256); Col_paletteToRGB(Abs:C99(PON_Color_NotEditable_L)\256))  // **Replaced o OBJECT SET COLOR([NTI_ELEM_BIN_INSP]ELEM_QTYSTATE1; PON_Color_NotEditable_L)
					OBJECT SET RGB COLORS:C628([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13; Col_paletteToRGB(Abs:C99(PON_Color_NotEditable_L)%256); Col_paletteToRGB(Abs:C99(PON_Color_NotEditable_L)\256))  // **Replaced o OBJECT SET COLOR([NTI_ELEM_BIN_INSP]ELEM_PCTSTATE2; PON_Color_NotEditable_L)
					
					If ([NTI_ELEM_BIN_INSP:183]ELEM_QorP:16)
						//showing quantites
						[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18:=Round:C94([NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20; PON_RoundQ_L)
						If ([NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18<0)
							// Warn that there is an error!
							ALERT:C41("Quantities in States do not add up correctly with Total Quantity!!! Please Adjust!")
						End if 
						[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE3:14:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
						[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE4:15:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
						[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13:=100-[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE3:14-[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE4:15
					Else 
						//if we are showing Percentages - recalc quantities based on percentages leave percentages as is
						[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19:=Round:C94((([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE3:14*[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21)/100); PON_RoundQ_L)
						[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20:=Round:C94((([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE4:15*[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21)/100); PON_RoundQ_L)
						[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18:=[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20
						If ([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13=0)
							[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
						Else 
							ALERT:C41("Quantities in States 2,3,4 adjusted according to current Percentages!")
						End if 
					End if 
					
				Else 
					
					If ([NTI_ELEM_BIN_INSP:183]ELEM_QorP:16)
						
						[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE1:17:=[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20
						If ([NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE1:17<0)
							// Warn that there is an error!
							ALERT:C41("Quantities in States do not add up correctly with Total Quantity!!! Please Adjust!")
						End if 
						[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
						[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE3:14:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
						[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE4:15:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
						[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE1:12:=100-[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13-[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE3:14-[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE4:15
						
					Else 
						//if we are showing Percentages - recalc quantities based on percentages leave percentages as is
						[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19:=Round:C94((([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE3:14*[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21)/100); PON_RoundQ_L)
						[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20:=Round:C94((([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE4:15*[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21)/100); PON_RoundQ_L)
						[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18:=Round:C94((([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE2:13*[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21)/100); PON_RoundQ_L)
						[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE1:17:=[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE2:18-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE3:19-[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE4:20
						If ([NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE1:12=0)
							[NTI_ELEM_BIN_INSP:183]ELEM_PCTSTATE1:12:=Round:C94(100*[NTI_ELEM_BIN_INSP:183]ELEM_QTYSTATE1:17/[NTI_ELEM_BIN_INSP:183]ELEM_QUANTITY:21; PON_RoundP_L)
						Else 
							ALERT:C41("Quantities in States 1,2,3,4 adjusted according to current Percentages!")
						End if 
						
					End if 
					
				End if 
			End if 
		End if 
		
End case 